# Site settings
name: 小草
location: 北京
company: IBM
position: Java开发工程师
github: https://hixiaocao.github.io/hi/
facebook: https://www.facebook.com/
phone: 1529346xxxx
email: 2375635198@qq.com

baseurl: "/hi"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

